"""EventGS demo: event-stream + video-stream joint dynamic 3DGS reconstruction.

This demo runs the full EventGS pipeline on a real-world dynamic video with
synchronized synthetic events (generated by the physical event simulator in
`event_video_dataset.py`, the v2e/ESIM-style approach used by DEGS, ERF-GS,
and EdMCGS when a real event camera is unavailable).

Pipeline:
  1. Load a synchronized (APS frames, DVS events) dataset.
  2. Build a baseline 3DGS scene G0 by fitting Gaussians to the first APS
     frame (a static-camera snapshot of the scene at t=0). This is the
     "known high-fidelity baseline" in the EventGS formulation; here we
     build it from the first frame for the prototype.
  3. For each subsequent frame, use the events between the previous and
     current frame to predict per-Gaussian motion increments (Layer 1:
     feed-forward prior + Layer 2: online refinement against the event-
     consistency loss), with the current APS frame as an intermittent
     keyframe (Layer 3: photometric alignment).
  4. Evaluate: render the deformed scene at each frame and compare to the
     APS frame (PSNR), and report the event-consistency loss.

This demonstrates the core EventGS claim: events drive the high-temporal-
resolution dynamic update, while the video stream provides absolute-
intensity keyframe anchors.

Run:
    python -m model.demo_event_video --npz data/event_video/jellyfish_events.npz
    python -m model.demo_event_video --npz data/event_video/jellyfish_events.npz --steps 200 --frames 10
"""
from __future__ import annotations
import argparse
import math
import torch
import torch.nn.functional as F

from model.torch_rasterizer import render_orth
from model.event_dyn import EventDynModel, event_consistency_loss
from model.event_video_dataset import EventVideoDataset


def build_baseline_from_frame(frame_rgb: torch.Tensor, H: int, W: int,
                              N: int = 800, device: str = 'cpu'):
    """Build a baseline 3DGS scene G0 by scattering Gaussians on a grid
    and initializing their colors to match the first APS frame.

    This is a minimal stand-in for a real offline GS reconstruction; the
    EventGS formulation assumes G0 is given, and here we construct it from
    the first video frame so the demo is self-contained.
    """
    # Grid of Gaussians in the y=0.5 plane.
    gh = int(math.sqrt(N * H / W))
    gw = N // gh
    yy = torch.linspace(-0.9, 0.9, gh, device=device)
    xx = torch.linspace(-0.9, 0.9, gw, device=device)
    gy, gx = torch.meshgrid(yy, xx, indexing='ij')
    means = torch.stack([gx.reshape(-1), torch.full((gh*gw,), 0.5, device=device),
                         gy.reshape(-1)], dim=-1)[:N]
    N = means.shape[0]
    # Project to pixel coords (ortho: x->u, z->v).
    uv = torch.stack([(means[:, 0] * 0.5 + 0.5) * (W - 1),
                      (1.0 - (means[:, 2] * 0.5 + 0.5)) * (H - 1)], dim=-1)
    # Sample the frame to get per-Gaussian colors.
    ui = uv[:, 0].long().clamp(0, W - 1)
    vi = uv[:, 1].long().clamp(0, H - 1)
    colors = frame_rgb[:, vi, ui].clamp(0, 1).T  # [N,3]
    opacity = torch.full((N, 1), 0.9, device=device)
    scales = torch.full((N, 3), 0.04, device=device)
    rot = torch.zeros(N, 4, device=device); rot[:, 0] = 1.0
    # Per-Gaussian feature = position + color.
    feat = torch.cat([means, colors], dim=-1)
    feat = torch.cat([feat, torch.zeros(N, 64 - feat.shape[1], device=device)], dim=-1)
    return {
        'means3D': means.unsqueeze(0), 'rgb': colors.unsqueeze(0),
        'opacity': opacity.unsqueeze(0), 'scale': scales.unsqueeze(0),
        'rot': rot.unsqueeze(0), 'uv': uv.unsqueeze(0), 'feat': feat.unsqueeze(0),
        'bg': torch.full((3,), 0.1, device=device),
    }


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('--npz', default='data/event_video/jellyfish_events.npz')
    ap.add_argument('--frames', type=int, default=8, help='number of frames to process')
    ap.add_argument('--steps', type=int, default=150, help='refinement steps per frame')
    ap.add_argument('--N', type=int, default=800, help='number of baseline Gaussians')
    ap.add_argument('--lambda_photo', type=float, default=5.0)
    ap.add_argument('--lambda_cmax', type=float, default=0.02)
    args = ap.parse_args()

    device = 'cuda' if torch.cuda.is_available() else 'cpu'
    print(f"Device: {device}")

    ds = EventVideoDataset(args.npz, device=device)
    H, W = ds.H, ds.W
    print(f"Dataset: {ds.T} frames, {ds.events.shape[0]} events, {H}x{W}")
    n_frames = min(args.frames, ds.T - 1)

    # --- Build baseline G0 from the first APS frame. ---
    frame0 = ds.frame_rgb(0)
    scene = build_baseline_from_frame(frame0, H, W, N=args.N, device=device)
    color_t0, _, _ = render_orth(
        scene['means3D'][0], scene['rgb'][0], scene['opacity'][0],
        scene['scale'][0], scene['rot'][0], H, W, bg=scene['bg'])
    scene['render_t0'] = color_t0.unsqueeze(0)
    print(f"Baseline G0: {args.N} Gaussians, rendered mean intensity {color_t0.mean():.3f}")

    # --- Feed-forward event decoder (Layer 1), reused across frames. ---
    model = EventDynModel(gauss_dim=64, event_dim=64, hidden=128, forder=2,
                          num_bins=5, polarity_split=True, use_pm=True,
                          contrast=ds.contrast).to(device)
    opt = torch.optim.AdamW(model.parameters(), lr=5e-3, weight_decay=1e-4)

    # Precompute pixel->Gaussian assoc for CMax (static camera).
    from model.contrast_max import pixel_to_gaussian_assoc, contrast_maximization_loss
    assoc = pixel_to_gaussian_assoc(scene['uv'], H, W)

    results = []
    for fi in range(1, n_frames + 1):
        # Events between previous frame and this frame.
        events = ds.events_between(fi - 1, fi)
        n_ev = events['pos'].shape[0]
        # APS keyframe for this frame (the "video stream").
        frame_i = ds.frame_rgb(fi)

        # Normalize event timestamps to [0,1] for the decoder.
        if n_ev > 0:
            ev = events.copy()
            t_min = float(events['t_min']); t_max = float(events['t_max'])
            ev['pos'] = events['pos'].clone()
            ev['pos'][:, 2] = (events['pos'][:, 2] - t_min) / (t_max - t_min + 1e-6)
            ev['t_min'] = torch.tensor(0.0, device=device)
            ev['t_max'] = torch.tensor(1.0, device=device)
        else:
            ev = events

        # --- Layer 1: feed-forward prior (warm start, few steps). ---
        t_query = torch.tensor([[1.0]], device=device)
        for _ in range(30):
            opt.zero_grad()
            out = model(scene, ev, t_query, render_orth, H, W)
            out['loss'].backward()
            opt.step()

        # --- Layer 2: online refinement of dmu against event + keyframe loss. ---
        with torch.no_grad():
            out = model(scene, ev, t_query, render_orth, H, W)
        dmu = out['increments']['dmu'].detach().clone().requires_grad_(True)
        opt_r = torch.optim.Adam([dmu], lr=5e-3)
        last_event = 0.0; last_photo = 0.0; last_cmax = 0.0
        for step in range(args.steps):
            opt_r.zero_grad()
            means3D = scene['means3D'] + dmu
            color, _, _ = render_orth(means3D[0], scene['rgb'][0], scene['opacity'][0],
                                      scene['scale'][0], scene['rot'][0], H, W,
                                      bg=scene['bg'])
            render_t1 = color.unsqueeze(0)
            loss_event, m = event_consistency_loss(scene['render_t0'], render_t1, ev,
                                                   contrast=ds.contrast)
            loss_photo = F.l1_loss(render_t1, frame_i.unsqueeze(0))
            loss = loss_event + args.lambda_photo * loss_photo
            # CMax regularizer.
            if args.lambda_cmax > 0 and n_ev > 0:
                u1 = (means3D[0][:, 0] * 0.5 + 0.5) * (W - 1)
                v1 = (1.0 - (means3D[0][:, 2] * 0.5 + 0.5)) * (H - 1)
                uv_t1 = torch.stack([u1, v1], dim=-1).unsqueeze(0)
                du = uv_t1 - scene['uv']
                ev_xy = ev['pos'][:, :2].long()
                ev_assoc = assoc[0, ev_xy[:, 1].clamp(0, H-1), ev_xy[:, 0].clamp(0, W-1)]
                loss_cmax = contrast_maximization_loss(ev, du, ev_assoc, H, W, sigma=2.0)
                loss = loss + args.lambda_cmax * loss_cmax
                last_cmax = loss_cmax.item()
            loss = loss + 1e-4 * dmu.abs().mean()
            loss.backward()
            opt_r.step()
            last_event = loss_event.item()
            last_photo = loss_photo.item()

        # --- Evaluate: render deformed scene and compare to APS frame. ---
        with torch.no_grad():
            means3D = scene['means3D'] + dmu
            pred, _, _ = render_orth(means3D[0], scene['rgb'][0], scene['opacity'][0],
                                     scene['scale'][0], scene['rot'][0], H, W,
                                     bg=scene['bg'])
            mse = ((pred - frame_i) ** 2).mean()
            psnr = 10 * torch.log10(1.0 / (mse + 1e-12))
            # Also PSNR of the static baseline (no motion) for comparison.
            mse0 = ((scene['render_t0'][0] - frame_i) ** 2).mean()
            psnr0 = 10 * torch.log10(1.0 / (mse0 + 1e-12))
        results.append({
            'frame': fi, 'events': n_ev,
            'event_loss': last_event, 'photo_loss': last_photo,
            'cmax_loss': last_cmax,
            'psnr_eventgs': psnr.item(), 'psnr_static': psnr0.item(),
            'dmu_norm': dmu.norm(dim=-1).mean().item(),
        })
        print(f"frame {fi:2d}: ev={n_ev:5d} L_ev={last_event:.4f} L_photo={last_photo:.4f} "
              f"L_cmax={last_cmax:.2f} |dmu|={dmu.norm(dim=-1).mean():.4f} "
              f"PSNR EventGS={psnr.item():.2f} dB | static={psnr0.item():.2f} dB")

        # Advance: the current deformed scene becomes the baseline for the
        # next window (the scene "tracks" the dynamics).
        scene['means3D'] = means3D.detach()
        scene['render_t0'] = pred.detach().unsqueeze(0)
        # Recompute uv for the moved Gaussians.
        u1 = (scene['means3D'][0][:, 0] * 0.5 + 0.5) * (W - 1)
        v1 = (1.0 - (scene['means3D'][0][:, 2] * 0.5 + 0.5)) * (H - 1)
        scene['uv'] = torch.stack([u1, v1], dim=-1).unsqueeze(0)

    # Summary.
    import numpy as np
    ps = [r['psnr_eventgs'] for r in results]
    ps0 = [r['psnr_static'] for r in results]
    print("\n=== Summary ===")
    print(f"Mean PSNR EventGS: {np.mean(ps):.2f} dB  (static baseline: {np.mean(ps0):.2f} dB)")
    print(f"Mean improvement: {np.mean(ps) - np.mean(ps0):+.2f} dB")
    print(f"Total events used: {sum(r['events'] for r in results)}")

    # Save results.
    import json
    with open('data/event_video/demo_results.json', 'w') as f:
        json.dump(results, f, indent=2)
    print("Results saved to data/event_video/demo_results.json")


if __name__ == '__main__':
    main()
